### ISSUE TITLE
Make the `promptlayer_api_call` run in the background

### ISSUE THREAD

**Issue by Jped** [MagnivOrg/prompt-layer-library#7]
Right now we [wait for the call to be completed](https://github.com/MagnivOrg/prompt-layer-library/blob/b984ae9ed86018c72841173d04b3da0be3333658/promptlayer/utils.py#L59), but we dont even do anything with the response (other than warn if there was an issue), we should be doing this in the background to speed things up. 

I am thinking we do some simple python threading, create a thread that runs the process in the background, and then immediately return the openAI request

**Comment by abubakarsohail** [comment]
@Jped the network call itself is dependent on the network call to OpenAI and since this is the last I/O bound call in the process, I think we cannot optimize this in the background. We could hack and call it in a daemon thread but that won't guarantee it's execution because
![image](https://user-images.githubusercontent.com/20099503/223050439-d731496a-8dee-4c24-b6ad-d3d498db2dcf.png)
Even if we do this in a thread, any remaining threads block the current execution and since this is the last network call in the process, it will still block and yield no results in optimization.

**Comment by Jped** [comment]
Hmm I hear, lets revisit this another way then.
